spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://52.26.176.218:3306/fridge_nsa
    username: poet
    password: poets
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: validate

multipart:
  maxFileSize: 15MB
  maxRequestSize: 15MB