spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fridge_nsa
    username: root
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: update

multipart:
  maxFileSize: 15MB
  maxRequestSize: 15MB